import { ListOfOrders } from "./order";


export const OrdersDetails: ListOfOrders[] = [
    { id:1, userName: 'nafel', fullName: 'Ghosdfst reisfdder', productOrder: 'banana,soap,ampalaya',
    totalOrder: 3 , location:'Sogod', status:'pending', action:'active'},
    { id:2, userName: 'anfel', fullName: 'Ghossdft resdfider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 4 , location:'Sogod', status:'pending', action:'active'},
    { id:3, userName: 'anael', fullName: 'Ghosdfst resdfider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 5 , location:'Sogod', status:'pending', action:'active'},
    { id:4, userName: 'aafel', fullName: 'Ghsdfost resfider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 6 , location:'Sogsdfaod', status:'pending', action:'active'},
    { id:5, userName: 'ansadfael', fullName: 'Ghosfst resdfider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 6 , location:'Sosfagod', status:'pending', action:'active'},
    { id:6, userName: 'anaasdffel', fullName: 'Ghsdfost reider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 6 , location:'Sofgod', status:'pending', action:'active'},
    { id:7, userName: 'anasadffel', fullName: 'Ghossdt reider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 6 , location:'Sodgod', status:'pending', action:'active'},
    { id:8, userName: 'anasdfafel', fullName: 'Ghdfost reider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 2 , location:'Sogsod', status:'pending', action:'active'},
    { id:9, userName: 'anaafdafel', fullName: 'Ghossdft reider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 6 , location:'Sogod', status:'pending', action:'active'},
    { id:10, userName: 'adsfanafel', fullName: 'Gsdsfhost reider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 7 , location:'Sogod', status:'pending', action:'active'},
    { id:11, userName: 'anafafel', fullName: 'Ghsdfost resfider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 8 , location:'Sogod', status:'pending', action:'active'},
    { id:12, userName: 'anafel', fullName: 'Ghoafst reisfder', productOrder: 'banana,soap,ampalaya',
    totalOrder: 9 , location:'Sogod', status:'pending', action:'active'},
    { id:13, userName: 'anaaffel', fullName: 'Gasdfhost rdeider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 4 , location:'Sogod', status:'pending', action:'active'},
    { id:14, userName: 'anafsafel', fullName: 'Ghost asreider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 4 , location:'Sogod', status:'pending', action:'active'},
    { id:15, userName: 'anafdsfel', fullName: 'Ghost asdfreider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 1 , location:'Sogod', status:'pending', action:'active'},
    { id:16, userName: 'anafsdfel', fullName: 'Ghost sreider', productOrder: 'banana,soap,ampalaya',
    totalOrder: 4 , location:'Sogod', status:'pending', action:'active'}
]
