import { ProductDetail, ProductHome  } from './product-local'


export const NewProductsDetails: ProductHome[] = [
  { id:1, name: 'Pork',insert:"home", type:"feature", price: {new:500, old:700}, url: './assets/images/featured/featured/feature-1.jpg' },
      { id:2, name:'Banana',insert:"home",type:"feature", price: {new: 1500, old: false}, url: './assets/images/featured/featured/feature-2.jpg' },
      { id:3, name:'Guava', insert:"home",type:"feature", price: {new:2500, old:2900}, url: './assets/images/featured/featured/feature-3.jpg' },
      { id:4, name:'Watermelon',insert:"home",type:"feature", price: {new:4500, old:false}, url: './assets/images/featured/featured/feature-4.jpg'},
      { id:5, name: 'Grapes',insert:"home", type:"latest", price: {new:200, old:700}, url: './assets/images/featured/latest/latest-1.png' },
      { id:6, name:'Hamburger',insert:"home", type:"latest", price: {new: 100, old: false}, url: './assets/images/featured/latest/latest-2.png' },
      { id:7, name:'Mango',insert:"home", type:"latest", price: {new:70, old:80}, url: './assets/images/featured/latest/latest-3.png' },
      { id:8, name:'Apple',insert:"home", type:"latest", price: {new:40, old:false}, url: './assets/images/featured/latest/latest-4.png'},
      { id:8, name: 'Fruits',insert:"home",type:"top", price: {new:100, old:700}, url: './assets/images/featured/top/product-1.png' },
      { id:9, name:'Apple',insert:"home",type:"top", price: {new: 50, old: false}, url: './assets/images/featured/top/product-4.png' },
      { id:10, name:'Milk',insert:"home",type:"top", price: {new:160, old:2900}, url: './assets/images/featured/top/product-3.png' },
      { id:11, name:'Juice',insert:"home",type:"top", price: {new:45, old:false}, url: './assets/images/featured/top/product-2.png' },      
]


export const ProductsDetails: ProductDetail[] = [
      {id: 1, price:40, name: 'Yase' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-1.jpg'},
			{id: 2, price:40,name: 'Strawberry' , insert:"supermarket",type:"all",url: 'assets/images/featured/feature-2.jpg'},
			{id: 3, price:60,name: 'Chili' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-3.jpg'},
			{id: 4, price:70,name: 'Cabbage' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-4.jpg'},
			{id: 5, price:90,name: 'Tomato' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-5.jpg'},
			{id: 6, price:100,name: 'Brocholli' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-6.jpg'},
			{id: 7,price:130, name: 'Carrots' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-7.jpg'},
			{id: 8, price:230,name: 'Juice' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-8.jpg'},
			{id: 9, price:130,name: 'Onion' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-1.jpg'},
			{id: 10, price:200,name: 'Apple' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-2.jpg'},
			{id: 11, price:390,name: 'Garlic' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-3.jpg'},
      {id: 12, price:180,name: 'Chili Pepper' ,insert:"supermarket",type:"all", url: 'assets/images/featured/feature-4.jpg'},
      {id: 13, price:40, name: 'Pepper' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-6.jpg'},
			{id: 14, price:42, name: 'Strawberry' , insert:"supermarket",type:"vegetable",url: 'assets/images/featured/feature-8.jpg'},
			{id: 15, price:30, name: 'Chili' , insert:"supermarket",type:"vegetable",url: 'assets/images/featured/feature-7.jpg'},
			{id: 16,price:50, name: 'Cabbage' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-6.jpg'},
			{id: 17, price:50, name: 'Tomato' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-5.jpg'},
			{id: 18, price:80, name: 'Brocholli' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-4.jpg'},
			{id: 19, price:80, name: 'Carrots' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-3.jpg'},
			{id: 20, price:80, name: 'Juice' , insert:"supermarket",type:"vegetable",url: 'assets/images/featured/feature-2.jpg'},
			{id: 21,price:80, name: 'Onion' , insert:"supermarket",type:"vegetable",url: 'assets/images/featured/feature-1.jpg'},
			{id: 22, price:100, name: 'Apple' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-6.jpg'},
			{id: 23, price:130, name: 'Garlic' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-8.jpg'},
      {id: 24,price:230, name: 'Chili Pepper' ,insert:"supermarket",type:"vegetable", url: 'assets/images/featured/feature-2.jpg'},
      {id: 25, price:300 ,name: 'Pepper' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-4.jpg'},
			{id: 26, price:30, name: 'Strawberry' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-5.jpg'},
			{id: 27, price:20, name: 'Chili' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-6.jpg'},
			{id: 28, price:50, name: 'Cabbage' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-7.jpg'},
			{id: 29, price:60, name: 'Tomato' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-8.jpg'},
			{id: 30, price:70, name: 'Brocholli' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-1.jpg'},
			{id: 31, price:80, name: 'Carrots' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-2.jpg'},
			{id: 32, price:90, name: 'Juice' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-3.jpg'},
			{id: 33, price:100, name: 'Onion' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-4.jpg'},
			{id: 34, price:120, name: 'Apple' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-5.jpg'},
			{id: 35, price:130, name: 'Garlic' , insert:"supermarket",type:"fruits",url: 'assets/images/featured/feature-4.jpg'},
      {id: 36, price:90, name: 'Chili Pepper' ,insert:"supermarket",type:"fruits", url: 'assets/images/featured/feature-8.jpg'},
      {id: 37, price:40, name: 'Pepper' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/204'},
      {id: 38, price:50, name: 'Strawberry' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/200'},
      {id: 39, price:60, name: 'Chili' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/201'},
      {id: 40, price:70, name: 'Cabbage' ,insert:"restaurant",type:"all", url: 'assets/images/featured/feature-4.jpg'},
      {id: 41, price:80, name: 'Tomato' ,insert:"restaurant",type:"all",url: 'assets/images/featured/feature-5.jpg'},
      {id: 42, price:90, name: 'Brocholli' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/202'},
      {id: 43, price:100, name: 'Carrots' ,insert:"restaurant",type:"all", url: 'assets/images/featured/feature-7.jpg'},
      {id: 44, price:410, name: 'Juice' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/203'},
      {id: 45, price:420, name: 'Onion' ,insert:"restaurant",type:"all", url: 'assets/images/featured/feature-1.jpg'},
      {id: 46, price:140, name: 'Apple' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/205'},
      {id: 47, price:430, name: 'Garlic' ,insert:"restaurant",type:"all", url: 'assets/images/featured/feature-3.jpg'},
      {id: 48, price:440, name: 'Chili Pepper' ,insert:"restaurant",type:"all", url: 'https://picsum.photos/206'},
      {id: 49, price:440, name: 'Pepper' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-6.jpg'},
			{id: 50, price:40, name: 'Strawberry' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-8.jpg'},
			{id: 51, price:20, name: 'Chili' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-7.jpg'},
			{id: 52, price:10, name: 'Cabbage' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-6.jpg'},
			{id: 53, price:40, name: 'Tomato' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-5.jpg'},
			{id: 54, price:50, name: 'Brocholli' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-4.jpg'},
			{id: 55, price:50, name: 'Carrots' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-3.jpg'},
			{id: 56, price:90, name: 'Juice' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-2.jpg'},
			{id: 57, price:100, name: 'Onion' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-1.jpg'},
			{id: 58, price:140, name: 'Apple' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-6.jpg'},
			{id: 59, price:100, name: 'Garlic' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-8.jpg'},
			{id: 60, price:32, name: 'Chili Pepper' ,insert:"restaurant",type:"food", url: 'assets/images/featured/feature-2.jpg'},
      {id: 61, price:40, name: 'Pepper' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-4.jpg'},
			{id: 62, price:35, name: 'Strawberry' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-5.jpg'},
			{id: 63, price:45, name: 'Chili' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-6.jpg'},
			{id: 64, price:49, name: 'Cabbage' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-7.jpg'},
			{id: 65, price:12, name: 'Tomato' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-8.jpg'},
			{id: 66, price:44, name: 'Brocholli' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-1.jpg'},
			{id: 67, price:46, name: 'Carrots' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-2.jpg'},
			{id: 68, price:23, name: 'Juice' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-3.jpg'},
			{id: 69, price:43, name: 'Onion' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-4.jpg'},
			{id: 70, price:52, name: 'Apple' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-5.jpg'},
			{id: 71, price:76, name: 'Garlic' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-4.jpg'},
			{id: 72, price:89, name: 'Chili Pepper' ,insert:"restaurant",type:"desserts", url: 'assets/images/featured/feature-8.jpg'}, 
    ]


export const ProductSpecialItems = [
  {id: 12, name: 'Pepper' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-1.jpg'},
			{id: 23, name: 'Strawberry' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-2.jpg'},
			{id: 13, name: 'Chili' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-3.jpg'},
			{id: 14, name: 'Cabbage' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-4.jpg'},
			{id: 15, name: 'Tomato' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-5.jpg'},
			{id: 16, name: 'Brocholli' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-6.jpg'},
			{id: 17, name: 'Carrots' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-7.jpg'},
			{id: 18, name: 'Juice' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-8.jpg'},
			{id: 19, name: 'Onion' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-9.jpg'},
			{id: 20, name: 'Apple' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-10.jpg'},
			{id: 21, name: 'Garlic' ,insert:"unknown",type:"none", url: 'assets/images/spices/product-11.jpg'},
			{id: 22, name: 'Chili Pepper' , url: 'assets/images/spices/product-12.jpg'},
]


export const DisplayCarouselImage = ['assets/images/img1.jpg','assets/images/img2.jpg'
,'assets/images/img3.jpg'];